name: CI

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  app-build:
    name: App Build (ESP-IDF)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build app
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          target: esp32c6
          path: "."
          command: |
            idf.py set-target esp32c6 build -D CCACHE_ENABLE=1
